name: Lab02 Reuse and Artifacts
run-name: Lab02 - ${{ github.actor }} is calling Composite Actions 🚀
permissions: read-all
on:
  workflow_dispatch:
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      # Check out the git repository
      - name: Checkout
        uses: actions/checkout@v4
        # Run template with parameters
      - name: Run hello world
        run: echo "🎉 Step of the job is running on ${{ runner.os }}!"
      - name: Build .NET App
        uses: ./.github/actions/build-dotnet-app
        with:
          folder-path: "apps/update-app"
          run-tests: "true"
          dotnet-version: "8.0"
          output-directory-path: "${{ github.workspace }}/output"

  # trigger-greeter:
  #   uses: ./.github/actions/greeter.yml
  #   with:
  #     person-name: "${{ github.actor }}"
