name: Lab01 Variables and Secrets
run-name: Lab01 - ${{ github.actor }} is testing variables and secrets 🚀
permissions: read-all
on:
  workflow_dispatch:
jobs:
  example-job:
    runs-on: [ubuntu-latest]
    env:
      MY_VARIABLE: "Hello, Github Actions! JEE!"
    steps:
      - name: Print my variable
        run: echo "${MY_VARIABLE}"

      - name: Print my secret
        run: echo "$DEMO_SECRET"
        env:
          DEMO_SECRET: ${{ secrets.DEMO_SECRET }}
