name: Lab10 SCA
run-name: Lab10 - ${{ github.actor }} is finding vulns🚀
permissions: read-all
on:
  workflow_dispatch:
jobs:
  depchecktest:
    runs-on: ubuntu-latest
    steps:
      #Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
      # Run OWASP Dependency check
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: "ci-security"
          path: "."
          format: "HTML"
          out: "reports" # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
        # Use always() to ensure that even if the above fails on threshold the results are uploaded
      - name: Upload Test results
        uses: actions/upload-artifact@master
        if: ${{ always() }}
        with:
          name: OWASP Dependency Check report
          path: ${{github.workspace}}/reports
